name: Multi Arch CI Build
on:
  release:
    types:
      - created
  push:
    tags:
      - 'v*.*.*'
      - '*.*.*'
    branches:
      - 'develop'
permissions:
  contents: read
  packages: write
jobs:
  gradle-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Gradle Validation
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - run: chmod +x ./gradlew
      - run: gradle build -x test
        env:
          GHCR_ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Prepare Metadata for Docker image
        id: docker-metadata
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/mayanksoni1996/portainer-service-deployer

          tags: |
            type=schedule
            type=ref,event=pr
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/aarch64
          push: ${{github.event_name != 'pull_request' }}
          tags: ${{steps.docker-metadata.outputs.tags}}
          labels: ${{steps.docker-metadata.outputs.labels}}